SQLALCHEMY_DATABASE_URI = 'mysql://wargame:wargame123@localhost:3306/wargame?charset=utf8'

HOST = '0.0.0.0'
PORT = 10101
SERVER_NAME = HOST + ':' + str(PORT)
SECRET_KEY = 'development-key'
SQLALCHEMY_TRACK_MODIFICATIONS = True
MAX_CONTENT_LENGTH = 5 * 1024 * 1024
TRAP_BAD_REQUEST_ERRORS = True
SQLALCHEMY_POOL_RECYCLE = 3600
